contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #sylensmodule channel"
    url: https://nfcore.slack.com/channels/sylensmodule
    about: Discussion about the nf-core/sylensmodule pipeline
